### ISSUE TITLE
broken links in readme

### ISSUE THREAD

**Issue by kalmarek** [paraynaud/PartitionedVectors.jl#14]
* There's no `CITATION.bib`
* Tutorial points to non-existing documentation

**Comment by paraynaud** [comment]
Hi @kalmarek, thanks for the remarks, I fixed both links.
Do I need to trigger the Registrator bot again, or [New package: PartitionedVectors v0.1.0 #72008 ](https://github.com/JuliaRegistries/General/pull/72008) will take the latest commit of main after the waiting period?

**Comment by kalmarek** [comment]
since the commit is touching only the README it doesn't really matter, does it? ;)

In any case you can start once again the same registration process (by mentioning JuliaRegistrator), it will just overwrite the registration pull.
